# NumPy and its operations

In [1]:
!pip install numpy

### Element-wise operations

In [2]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)
print(a - b)
print(a * b)
print(a / b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


### Scalar Operations

In [3]:
import numpy as np

a = np.array([1, 2, 3])

print(a + 2)
print(a * 3)

[3 4 5]
[3 6 9]


### Comparison Operations

In [4]:
import numpy as np

a = np.array([1, 2, 3, 4])

print(a > 2)
print(a == 2)

[False False  True  True]
[False  True False False]


### Logical Operations

In [5]:
import numpy as np

a = np.array([2, 3, 5, 7])

print((a > 2) & (a < 4))
print((a > 2) | (a < 4))
print(~(a < 4))

[False  True False False]
[ True  True  True  True]
[False False  True  True]


### Aggregation Operations

| Operation              | Function              |
|-----------------------|-----------------------|
| Sum                   | `np.sum(a)`           |
| Mean (Average)        | `np.mean(a)`          |
| Median                | `np.median(a)`        |
| Minimum               | `np.min(a)`           |
| Maximum               | `np.max(a)`           |
| Standard Deviation    | `np.std(a)`           |
| Variance              | `np.var(a)`           |
| Product               | `np.prod(a)`          |
| Cumulative Sum        | `np.cumsum(a)`        |
| Cumulative Product    | `np.cumprod(a)`       |
| Arg Min (index of min)| `np.argmin(a)`        |
| Arg Max (index of max)| `np.argmax(a)`        |
| Percentile            | `np.percentile(a, q)` |
| Quantile              | `np.quantile(a, q)`   |
| Count Non-zero        | `np.count_nonzero(a)` |
| Any (logical OR)      | `np.any(a)`           |
| All (logical AND)     | `np.all(a)`           |

In [6]:
import numpy as np

a = np.array([2, 4, 6, 9])
b = np.array([5, 7, 3])

print(np.sum(a))
print(np.sum(a) + np.sum(b))

21
36


#### Axis Concept

In [7]:
a = np.array([[1, 2],
             [3, 4]])

print(np.sum(a, axis = 0))       # Column-wise
print(np.sum(a, axis = 1))       # Row-wise

[4 6]
[3 7]


### Mathemnatical Functions

| Category                           | Functions                                                   |
| ---------------------------------- | ----------------------------------------------------------- |
| Basic Arithmetic                   | `np.add()`, `np.subtract()`, `np.multiply()`, `np.divide()` |
| Power & Roots                      | `np.power()`, `np.sqrt()`                                   |
| Exponential & Log                  | `np.exp()`, `np.log()`, `np.log10()`, `np.log2()`           |
| Absolute & Rounding                | `np.abs()`, `np.round()`, `np.floor()`, `np.ceil()`         |
| Trigonometric *(less used in ML)*  | `np.sin()`, `np.cos()`, `np.tan()`                          |
| Hyperbolic *(used in activations)* | `np.tanh()`, `np.sinh()`, `np.cosh()`                       |
| Clipping & Bounds                  | `np.clip()`                                                 |
| Sign & Comparison                  | `np.sign()`, `np.maximum()`, `np.minimum()`                 |
| NaN-safe Operations                | `np.nan_to_num()`, `np.isnan()`                             |

In [8]:
np.add(4,5)

np.int64(9)

### Dot Product

In [9]:
import numpy as np

a = np.array([1, 3, 4])
b = np.array([5, 2, 8])

print(np.dot(a, b))

43


### Matrix Multiplication

In [10]:
import numpy as np

a = np.array([[2, 4],
             [5, 3]])

b = np.array([[3, 7],
             [4, 2]])

print(np.matmul(a, b))
print(a @ b)

[[22 22]
 [27 41]]
[[22 22]
 [27 41]]


### BroadCasting

In [12]:
import numpy as np

a = np.array([[1, 2, 3],
             [4, 5, 6]])

b = np.array([1, 1, 2])         # NumPy automatically expands b

print(a + b)

[[2 3 5]
 [5 6 8]]


### Indexed-based Operations

In [14]:
import numpy as np

a = np.array([10, 30, 40, 20])

print(a[[1, 3]])

[30 20]


### Conditional Operations

In [15]:
import numpy as np

a = np.array([1, 2, 4, 5])

print(a[a > 2])

[4 5]
